//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vovinam.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vovinam.Resources.EnumText", typeof(EnumText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích hoạt.
        /// </summary>
        public static string ClubStatus_Active {
            get {
                return ResourceManager.GetString("ClubStatus.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa kích hoạt.
        /// </summary>
        public static string ClubStatus_InActive {
            get {
                return ResourceManager.GetString("ClubStatus.InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích hoạt.
        /// </summary>
        public static string CompanyStatus_Active {
            get {
                return ResourceManager.GetString("CompanyStatus.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa kích hoạt.
        /// </summary>
        public static string CompanyStatus_InActive {
            get {
                return ResourceManager.GetString("CompanyStatus.InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender.Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender.Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Á khoa.
        /// </summary>
        public static string KetQua_AKhoa {
            get {
                return ResourceManager.GetString("KetQua.AKhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa cập nhật.
        /// </summary>
        public static string KetQua_CapNhat {
            get {
                return ResourceManager.GetString("KetQua.CapNhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đậu.
        /// </summary>
        public static string KetQua_Dau {
            get {
                return ResourceManager.GetString("KetQua.Dau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rớt.
        /// </summary>
        public static string KetQua_Rot {
            get {
                return ResourceManager.GetString("KetQua.Rot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thủ khoa.
        /// </summary>
        public static string KetQua_ThuKhoa {
            get {
                return ResourceManager.GetString("KetQua.ThuKhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đậu vớt.
        /// </summary>
        public static string KetQua_Vot {
            get {
                return ResourceManager.GetString("KetQua.Vot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích hoạt.
        /// </summary>
        public static string UserStatus_Active {
            get {
                return ResourceManager.GetString("UserStatus.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa kích hoạt.
        /// </summary>
        public static string UserStatus_InActive {
            get {
                return ResourceManager.GetString("UserStatus.InActive", resourceCulture);
            }
        }
    }
}
