//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vovinam.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compete
    {
        public int Id { get; set; }
        public int LevelUpId1 { get; set; }
        public int LevelUpId2 { get; set; }
        public int ExaminationId { get; set; }
        public Gender Gender { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        public virtual LevelUp LevelUp { get; set; }
        public virtual LevelUp LevelUp1 { get; set; }
    }
}
