//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vovinam.Data
{
    using System;
    
    public enum CompanyStatus : int
    {
        InActive = 0,
        Active = 1
    }
}
