//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vovinam.Data
{
    using System;
    
    public enum KetQua : int
    {
        Dau = 0,
        Rot = 1,
        Vot = 2,
        ThuKhoa = 3,
        AKhoa = 4,
        CapNhat = 5
    }
}
