//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vovinam.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LevelUp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LevelUp()
        {
            this.Competes = new HashSet<Compete>();
            this.Competes1 = new HashSet<Compete>();
            this.LevelUpHistories = new HashSet<LevelUpHistory>();
        }
    
        public int Id { get; set; }
        public int Stt { get; set; }
        public Nullable<int> BirthDay { get; set; }
        public Gender Gender { get; set; }
        public int ClubId { get; set; }
        public int LevelId { get; set; }
        public Nullable<int> Weight { get; set; }
        public int ExaminationId { get; set; }
        public Nullable<int> QuyenId { get; set; }
        public Nullable<int> CobanId { get; set; }
        public Nullable<int> TheLucId { get; set; }
        public Nullable<int> SongLuyenId { get; set; }
        public Nullable<int> VodaoId { get; set; }
        public Nullable<int> DoiKhangId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public double Total { get; set; }
        public bool HasCompete { get; set; }
        public string Name { get; set; }
        public KetQua KetQua { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual CoBan CoBan { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compete> Competes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compete> Competes1 { get; set; }
        public virtual DoiKhang DoiKhang { get; set; }
        public virtual Examination Examination { get; set; }
        public virtual Level Level { get; set; }
        public virtual Quyen Quyen { get; set; }
        public virtual SongLuyen SongLuyen { get; set; }
        public virtual TheLuc TheLuc { get; set; }
        public virtual VoDao VoDao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LevelUpHistory> LevelUpHistories { get; set; }
    }
}
