//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vovinam.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LevelUpHistory
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public System.DateTime TimeCreate { get; set; }
        public int LevelUpId { get; set; }
        public string Name { get; set; }
        public string StudentName { get; set; }
        public double PointNew { get; set; }
        public double PointOld { get; set; }
    
        public virtual LevelUp LevelUp { get; set; }
    }
}
