//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vovinam.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Content { get; set; }
        public System.DateTime TimeCreate { get; set; }
        public Nullable<bool> Seen { get; set; }
        public bool Show { get; set; }
    
        public virtual User User { get; set; }
    }
}
