//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vovinam.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Hometown { get; set; }
        public int ClubId { get; set; }
        public int LevelId { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string Image { get; set; }
        public Nullable<Gender> Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> TimeDeleted { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public bool Tuition1 { get; set; }
        public bool Tuition2 { get; set; }
        public bool Tuition3 { get; set; }
        public bool Tuition4 { get; set; }
        public bool Tuition5 { get; set; }
        public bool Tuition6 { get; set; }
        public bool Tuition7 { get; set; }
        public bool Tuition8 { get; set; }
        public bool Tuition9 { get; set; }
        public bool Tuition10 { get; set; }
        public bool Tuition11 { get; set; }
        public bool Tuition12 { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Level Level { get; set; }
        public virtual School School { get; set; }
    }
}
