//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vovinam.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vovinamEntities : DbContext
    {
        public vovinamEntities()
            : base("name=vovinamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Group_Permission> Group_Permission { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<User_Permission> User_Permission { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Examination> Examinations { get; set; }
        public virtual DbSet<CoBan> CoBans { get; set; }
        public virtual DbSet<DoiKhang> DoiKhangs { get; set; }
        public virtual DbSet<Quyen> Quyens { get; set; }
        public virtual DbSet<SongLuyen> SongLuyens { get; set; }
        public virtual DbSet<TheLuc> TheLucs { get; set; }
        public virtual DbSet<VoDao> VoDaos { get; set; }
        public virtual DbSet<Compete> Competes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<LevelUpHistory> LevelUpHistories { get; set; }
        public virtual DbSet<LevelUp> LevelUps { get; set; }
    }
}
